## <font color="blue">3.0 - Cash Flow: Pre-Processing<font>
---

##### <font color="blue">Imports<font>
---

In [1]:
#import libraries
import pandas as pd
import numpy as np
from pandas import Series, DataFrame
import matplotlib.pyplot as plt
import matplotlib as mpl
from scipy import stats
import seaborn as sns
import matplotlib.ticker as mtick
%matplotlib notebook
%matplotlib inline


pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

##### <font color="blue">Joining Datasets<font>
---

In [203]:
#Reading in all cleaned datasets

idf = pd.read_parquet('Data/cleaned/income_cleaned.parquet')
pdf = pd.read_parquet('data/cleaned/population_cleaned.parquet')
vdf = pd.read_parquet('data/cleaned/vote_cleaned.parquet')
ldf = pd.read_parquet('data/cleaned/listings_cleaned.parquet')

<font color="blue">Changing column names for easy deletion, post merge<font>

In [204]:
pdf.rename(columns = {'County':'county'}, inplace = True)
vdf.rename(columns = {'County':'county'}, inplace = True)

<font color="blue">1st Merge: Income and Population. Same # of rows."<font>

In [205]:
merge1 = pd.concat([idf, pdf], axis=1)
merge1.head()

,County,W_HH_Income_<10k,"W_HH_Income_$10,000 to $14,999","W_HH_Income_$15,000 to $19,999","W_HH_Income_$20,000 to $24,999","W_HH_Income_$25,000 to $29,999","W_HH_Income_$30,000 to $34,999","W_HH_Income_$35,000 to $39,999","W_HH_Income_$40,000 to $44,999","W_HH_Income_$45,000 to $49,999","W_HH_Income_$50,000 to $59,999","W_HH_Income_$60,000 to $74,999","W_HH_Income_$75,000 to $99,999","W_HH_Income_$100,000 to $124,999","W_HH_Income_$125,000 to $149,999","W_HH_Income_$150,000 to $199,999","W_HH_Income_$200,000 or more",Median_HH_Income,Median_HH_Income_B_AA,Median_HH_Income_Asian,Median_HH_Income_White,Total_Income,Passive_Income,Active_Income,SE_Income,Non_SE_Income,county,Total population,Population Under 5 years,Population 5-9 years,Population 10-14 years,Population 15-19 years,Population 20-24 years,Population 25-29 years,Population 30-34 years,Population 35-39 years,Population 40-44 years,Population 45-49 years,Population 50-54 years,Population 55-59 years,Population 60-64 years,Population 65-69 years,Population 70-74 years,Population 75-79 years,Population 80-84 years,Population Over 85 years,Population 5-14 years,Population Under 15-17 years,Population Under 18 years,Population Under 18-24 years,Population Under 15-44 years,Population Under 16 years and over,Population 18 years and over,Population 21 years and over,Population 60 years and over,Population 62 years and over,Population 65 years and over,Population 75 years and over,Median age (years),Sex ratio (males per 100 females),Old-age dependency ratio,Child dependency ratio,Percent Under 5 years,Percent 5 to 9 years,Percent 10 to 14 years,Percent 15 to 19 years,Percent 20 to 24 years,Percent 25 to 29 years,Percent 30 to 34 years,Percent 35 to 39 years,Percent 40 to 44 years,Percent 45 to 49 years,Percent 50 to 54 years,Percent 55 to 59 years,Percent 60 to 64 years,Percent 65 to 69 years,Percent 70 to 74 years,Percent 75 to 79 years,Percent 80 to 84 years,Percent 85 years and over,Percent 5 to 14 years,Percent 15 to 17 years,Percent Under 18 years,Percent 18 to 24 years,Percent 15 to 44 years,Percent 16 years and over,Percent 18 years and over,Percent 21 years and over,Percent 60 years and over,Percent 62 years and over,Percent 65 years and over,Male Total population,Percent Male Under 5 years,Percent Male 5 to 9 years,Percent Male 10 to 14 years,Percent Male 15 to 19 years,Percent Male 20 to 24 years,Percent Male 25 to 29 years,Percent Male 30 to 34 years,Percent Male 35 to 39 years,Percent Male 40 to 44 years,Percent Male 45 to 49 years,Percent Male 50 to 54 years,Percent Male 55 to 59 years,Percent Male 60 to 64 years,Percent Male 65 to 69 years,Percent Male 70 to 74 years,Percent Male 75 to 79 years,Percent Male 80 to 84 years,Percent Male 85 years and over,Female Total population,Female population Under 5 years,Female population 5 to 9 years,Female population 10 to 14 years,Female population 5 to 19 years,Female population 20 to 24 years,Female population 25 to 29 years,Female population 30 to 34 years,Female population 35 to 39 years,Female population 40 to 44 years,Female population 45 to 49 years,Female population 50 to 54 years,Female population 55 to 59 years,Female population 60 to 64 years,Female population 65 to 69 years,Female population 70 to 74 years,Female population 75 to 79 years,Female population 80 to 84 years,Female population 85 years and over,Percent Female Under 5 years,Percent Female 5 to 9 years,Percent Female 10 to 14 years,Percent Female 15 to 19 years,Percent Female 20 to 24 years,Percent Female 25 to 29 years,Percent Female 30 to 34 years,Percent Female 35 to 39 years,Percent Female 40 to 44 years,Percent Female 45 to 49 years,Percent Female 50 to 54 years,Percent Female 55 to 59 years,Percent Female 60 to 64 years,Percent Female 65 to 69 years,Percent Female 70 to 74 years,Percent Female 75 to 79 years,Percent Female 80 to 84 years,Percent Female 85 years and over
0,Alameda,8196,4390,4467,3790,4459,4379,5268,4031,4554,9214,13425,23827,20314,16545,27660,63896,109729,59817.0,146259.0,126060,589180,173658,415522,73736.0,515444,Alameda,1648556,88016,91575,95952,95487,89838,115618,143781,139723,121234,111042,108383,102653,99204,79002,69229,42672,25545,29602,187527,56340,331883,128985,705681,1354894,1316673,1258792,345254,303367,246050,97819,38.8,98.2,23.0,31.0,5.3,5.6,5.8,5.8,5.4,0.0,8.7,8.5,7.4,6.7,6.6,6.2,6.0,4.8,4.2,2.6,1.5,1.8,11.4,3.4,20.1,7.8,42.8,82.2,79.9,76.4,20.9,18.4,14.9,816792,5.5,5.7,6.1,5.9,5.5,7.1,8.8,8.7,7.5,6.8,6.7,6.1,6.1,4.7,3.8,2.2,1.3,1.5,831764,43354,45027,46210,47105,45026,57614,71578,68448,60339,55336,53518,52820,49267,40914,38339,24930,14601,17338,5.2,5.4,5.6,5.7,5.4,6.9,8.6,8.2,7.3,6.7,6.4,6.4,5.9,4.9,4.6,3.0,1.8,2.1
1,Butte,3116,2692,2009,2772,3304,2121,2756,2462,2125,4222,7461,8441,4684,4557,5603,4994,64738,57410.0,73054.0,69995,81353,15432,65921,9729.0,71624,Butte,208309,10910,11370,12623,16972,20154,13880,12825,12716,12722,10175,10647,14755,10300,11588,12101,7422,3993,3156,23993,7499,42402,29627,89269,170370,165907,151999,48560,44300,38260,14571,36.8,98.2,30.0,33.2,5.2,5.5,6.1,8.1,9.7,6.7,6.2,6.1,6.1,4.9,5.1,7.1,4.9,5.6,5.8,3.6,1.9,1.5,11.5,3.6,20.4,14.2,42.9,81.8,79.6,73.0,23.3,21.3,18.4,103229,5.0,5.6,6.5,8.4,9.1,7.3,6.4,6.6,6.4,5.0,5.3,6.6,5.1,4.9,5.9,2.7,2.1,1.2,105080,5786,5587,5906,8329,10748,6351,6268,5950,6154,5010,5166,7901,5056,6531,5982,4600,1834,1921,5.5,5.3,5.6,7.9,10.2,6.0,6.0,5.7,5.9,4.8,4.9,7.5,4.8,6.2,5.7,4.4,1.7,1.8
2,Contra Costa,7706,3554,3324,2637,4055,4964,4665,4965,3805,9032,12882,21936,21811,14834,29224,59449,111080,72225.0,133284.0,125957,411560,114001,297559,58119.0,353441,Contra,1161413,61458,66656,80618,75261,65345,68537,75001,81772,80841,77314,80627,78870,75095,61104,54384,37585,21897,19048,147274,48630,257362,91976,446757,935414,904051,866212,269113,235792,194018,78530,40.4,96.6,27.3,36.2,5.3,5.7,6.9,6.5,5.6,5.9,6.5,7.0,7.0,6.7,6.9,6.8,6.5,5.3,4.7,3.2,1.9,1.6,12.7,4.2,22.2,7.9,38.5,80.5,77.8,74.6,23.2,20.3,16.7,570719,5.4,5.7,7.4,6.8,5.8,6.1,6.5,7.2,6.9,6.7,7.1,6.9,6.3,5.0,4.4,2.8,1.8,1.1,590694,30377,33844,38185,36522,32319,33868,37891,40596,41552,39195,40269,39679,38864,32460,29474,21360,11753,12486,5.1,5.7,6.5,6.2,5.5,5.7,6.4,6.9,7.0,6.6,6.8,6.7,6.6,5.5,5.0,3.6,2.0,2.1
3,El Dorado,2557,1800,1942,1464,1824,1166,1528,1814,766,3508,6250,8445,6770,5019,5844,11979,87491,NaN,119278.0,89321,74909,19414,55495,11183.0,63726,El Dorado,193221,9026,8829,14140,9734,9554,7741,11612,12806,11721,10578,12896,16070,15106,15986,11705,7379,3615,4723,22969,6151,38146,13137,63168,159055,155075,149787,58514,52272,43408,15717,45.7,98.9,38.9,34.2,4.7,4.6,7.3,5.0,4.9,4.0,6.0,6.6,6.1,5.5,6.7,8.3,7.8,8.3,6.1,3.8,1.9,2.4,11.9,3.2,19.7,6.8,32.7,82.3,80.3,77.5,30.3,27.1,22.5,96068,4.5,4.2,7.3,5.5,5.6,4.3,5.4,6.9,6.4,5.6,6.5,9.0,6.8,8.3,6.2,3.9,1.3,2.5,97153,4731,4779,7175,4450,4211,3613,6397,6175,5594,5178,6617,7418,8604,8039,5766,3672,2386,2348,4.9,4.9,7.4,4.6,4.3,3.7,6.6,6.4,5.8,5.3,6.8,7.6,8.9,8.3,5.9,3.8,2.5,2.4
4,Fresno,7937,4057,4351,5706,4707,4770,5130,4951,5177,8447,12873,17119,13133,9171,14618,13603,63656,47373.0,74149.0,77258,322646,41214,281432,33947.0,288699,Fresno,1013581,71998,79902,84738,77051,69163,74784,77348,71435,63999,55542,55065,54788,50048,43324,34722,22139,14428,13107,164640,48915,285553,97299,433780,761696,728028,685183,177768,157259,127720,49674,33.1,100.5,21.3,47.6,7.1,7.9,8.4,7.6,6.8,7.4,7.6,7.0,6.3,5.5,5.4,5.4,4.9,4.3,3.4,2.2,1.4,1.3,16.2,4.8,28.2,9.6,42.8,75.1,71.8,67.6,17.5,15.5,12.6,508152,7.3,8.5,8.1,7.6,6.9,7.5,7.7,7.3,6.3,5.5,5.5,5.5,4.7,4.1,3.2,1.9,1.3,0.8,505429,35139,36494,43678,38667,33854,36498,38046,34213,31820,27434,26962,26834,26017,22301,18651,12241,7582,8998,7.0,7.2,8.6,7.7,6.7,7.2,7.5,6.8,6.3,5.4,5.3,5.3,5.1,4.4,3.7,2.4,1.5,1.8

In [206]:
merge1.drop(['county'], axis = 1, inplace=True)

In [207]:
merge1.head(5)

,County,W_HH_Income_<10k,"W_HH_Income_$10,000 to $14,999","W_HH_Income_$15,000 to $19,999","W_HH_Income_$20,000 to $24,999","W_HH_Income_$25,000 to $29,999","W_HH_Income_$30,000 to $34,999","W_HH_Income_$35,000 to $39,999","W_HH_Income_$40,000 to $44,999","W_HH_Income_$45,000 to $49,999","W_HH_Income_$50,000 to $59,999","W_HH_Income_$60,000 to $74,999","W_HH_Income_$75,000 to $99,999","W_HH_Income_$100,000 to $124,999","W_HH_Income_$125,000 to $149,999","W_HH_Income_$150,000 to $199,999","W_HH_Income_$200,000 or more",Median_HH_Income,Median_HH_Income_B_AA,Median_HH_Income_Asian,Median_HH_Income_White,Total_Income,Passive_Income,Active_Income,SE_Income,Non_SE_Income,Total population,Population Under 5 years,Population 5-9 years,Population 10-14 years,Population 15-19 years,Population 20-24 years,Population 25-29 years,Population 30-34 years,Population 35-39 years,Population 40-44 years,Population 45-49 years,Population 50-54 years,Population 55-59 years,Population 60-64 years,Population 65-69 years,Population 70-74 years,Population 75-79 years,Population 80-84 years,Population Over 85 years,Population 5-14 years,Population Under 15-17 years,Population Under 18 years,Population Under 18-24 years,Population Under 15-44 years,Population Under 16 years and over,Population 18 years and over,Population 21 years and over,Population 60 years and over,Population 62 years and over,Population 65 years and over,Population 75 years and over,Median age (years),Sex ratio (males per 100 females),Old-age dependency ratio,Child dependency ratio,Percent Under 5 years,Percent 5 to 9 years,Percent 10 to 14 years,Percent 15 to 19 years,Percent 20 to 24 years,Percent 25 to 29 years,Percent 30 to 34 years,Percent 35 to 39 years,Percent 40 to 44 years,Percent 45 to 49 years,Percent 50 to 54 years,Percent 55 to 59 years,Percent 60 to 64 years,Percent 65 to 69 years,Percent 70 to 74 years,Percent 75 to 79 years,Percent 80 to 84 years,Percent 85 years and over,Percent 5 to 14 years,Percent 15 to 17 years,Percent Under 18 years,Percent 18 to 24 years,Percent 15 to 44 years,Percent 16 years and over,Percent 18 years and over,Percent 21 years and over,Percent 60 years and over,Percent 62 years and over,Percent 65 years and over,Male Total population,Percent Male Under 5 years,Percent Male 5 to 9 years,Percent Male 10 to 14 years,Percent Male 15 to 19 years,Percent Male 20 to 24 years,Percent Male 25 to 29 years,Percent Male 30 to 34 years,Percent Male 35 to 39 years,Percent Male 40 to 44 years,Percent Male 45 to 49 years,Percent Male 50 to 54 years,Percent Male 55 to 59 years,Percent Male 60 to 64 years,Percent Male 65 to 69 years,Percent Male 70 to 74 years,Percent Male 75 to 79 years,Percent Male 80 to 84 years,Percent Male 85 years and over,Female Total population,Female population Under 5 years,Female population 5 to 9 years,Female population 10 to 14 years,Female population 5 to 19 years,Female population 20 to 24 years,Female population 25 to 29 years,Female population 30 to 34 years,Female population 35 to 39 years,Female population 40 to 44 years,Female population 45 to 49 years,Female population 50 to 54 years,Female population 55 to 59 years,Female population 60 to 64 years,Female population 65 to 69 years,Female population 70 to 74 years,Female population 75 to 79 years,Female population 80 to 84 years,Female population 85 years and over,Percent Female Under 5 years,Percent Female 5 to 9 years,Percent Female 10 to 14 years,Percent Female 15 to 19 years,Percent Female 20 to 24 years,Percent Female 25 to 29 years,Percent Female 30 to 34 years,Percent Female 35 to 39 years,Percent Female 40 to 44 years,Percent Female 45 to 49 years,Percent Female 50 to 54 years,Percent Female 55 to 59 years,Percent Female 60 to 64 years,Percent Female 65 to 69 years,Percent Female 70 to 74 years,Percent Female 75 to 79 years,Percent Female 80 to 84 years,Percent Female 85 years and over
0,Alameda,8196,4390,4467,3790,4459,4379,5268,4031,4554,9214,13425,23827,20314,16545,27660,63896,109729,59817.0,146259.0,126060,589180,173658,415522,73736.0,515444,1648556,88016,91575,95952,95487,89838,115618,143781,139723,121234,111042,108383,102653,99204,79002,69229,42672,25545,29602,187527,56340,331883,128985,705681,1354894,1316673,1258792,345254,303367,246050,97819,38.8,98.2,23.0,31.0,5.3,5.6,5.8,5.8,5.4,0.0,8.7,8.5,7.4,6.7,6.6,6.2,6.0,4.8,4.2,2.6,1.5,1.8,11.4,3.4,20.1,7.8,42.8,82.2,79.9,76.4,20.9,18.4,14.9,816792,5.5,5.7,6.1,5.9,5.5,7.1,8.8,8.7,7.5,6.8,6.7,6.1,6.1,4.7,3.8,2.2,1.3,1.5,831764,43354,45027,46210,47105,45026,57614,71578,68448,60339,55336,53518,52820,49267,40914,38339,24930,14601,17338,5.2,5.4,5.6,5.7,5.4,6.9,8.6,8.2,7.3,6.7,6.4,6.4,5.9,4.9,4.6,3.0,1.8,2.1
1,Butte,3116,2692,2009,2772,3304,2121,2756,2462,2125,4222,7461,8441,4684,4557,5603,4994,64738,57410.0,73054.0,69995,81353,15432,65921,9729.0,71624,208309,10910,11370,12623,16972,20154,13880,12825,12716,12722,10175,10647,14755,10300,11588,12101,7422,3993,3156,23993,7499,42402,29627,89269,170370,165907,151999,48560,44300,38260,14571,36.8,98.2,30.0,33.2,5.2,5.5,6.1,8.1,9.7,6.7,6.2,6.1,6.1,4.9,5.1,7.1,4.9,5.6,5.8,3.6,1.9,1.5,11.5,3.6,20.4,14.2,42.9,81.8,79.6,73.0,23.3,21.3,18.4,103229,5.0,5.6,6.5,8.4,9.1,7.3,6.4,6.6,6.4,5.0,5.3,6.6,5.1,4.9,5.9,2.7,2.1,1.2,105080,5786,5587,5906,8329,10748,6351,6268,5950,6154,5010,5166,7901,5056,6531,5982,4600,1834,1921,5.5,5.3,5.6,7.9,10.2,6.0,6.0,5.7,5.9,4.8,4.9,7.5,4.8,6.2,5.7,4.4,1.7,1.8
2,Contra Costa,7706,3554,3324,2637,4055,4964,4665,4965,3805,9032,12882,21936,21811,14834,29224,59449,111080,72225.0,133284.0,125957,411560,114001,297559,58119.0,353441,1161413,61458,66656,80618,75261,65345,68537,75001,81772,80841,77314,80627,78870,75095,61104,54384,37585,21897,19048,147274,48630,257362,91976,446757,935414,904051,866212,269113,235792,194018,78530,40.4,96.6,27.3,36.2,5.3,5.7,6.9,6.5,5.6,5.9,6.5,7.0,7.0,6.7,6.9,6.8,6.5,5.3,4.7,3.2,1.9,1.6,12.7,4.2,22.2,7.9,38.5,80.5,77.8,74.6,23.2,20.3,16.7,570719,5.4,5.7,7.4,6.8,5.8,6.1,6.5,7.2,6.9,6.7,7.1,6.9,6.3,5.0,4.4,2.8,1.8,1.1,590694,30377,33844,38185,36522,32319,33868,37891,40596,41552,39195,40269,39679,38864,32460,29474,21360,11753,12486,5.1,5.7,6.5,6.2,5.5,5.7,6.4,6.9,7.0,6.6,6.8,6.7,6.6,5.5,5.0,3.6,2.0,2.1
3,El Dorado,2557,1800,1942,1464,1824,1166,1528,1814,766,3508,6250,8445,6770,5019,5844,11979,87491,NaN,119278.0,89321,74909,19414,55495,11183.0,63726,193221,9026,8829,14140,9734,9554,7741,11612,12806,11721,10578,12896,16070,15106,15986,11705,7379,3615,4723,22969,6151,38146,13137,63168,159055,155075,149787,58514,52272,43408,15717,45.7,98.9,38.9,34.2,4.7,4.6,7.3,5.0,4.9,4.0,6.0,6.6,6.1,5.5,6.7,8.3,7.8,8.3,6.1,3.8,1.9,2.4,11.9,3.2,19.7,6.8,32.7,82.3,80.3,77.5,30.3,27.1,22.5,96068,4.5,4.2,7.3,5.5,5.6,4.3,5.4,6.9,6.4,5.6,6.5,9.0,6.8,8.3,6.2,3.9,1.3,2.5,97153,4731,4779,7175,4450,4211,3613,6397,6175,5594,5178,6617,7418,8604,8039,5766,3672,2386,2348,4.9,4.9,7.4,4.6,4.3,3.7,6.6,6.4,5.8,5.3,6.8,7.6,8.9,8.3,5.9,3.8,2.5,2.4
4,Fresno,7937,4057,4351,5706,4707,4770,5130,4951,5177,8447,12873,17119,13133,9171,14618,13603,63656,47373.0,74149.0,77258,322646,41214,281432,33947.0,288699,1013581,71998,79902,84738,77051,69163,74784,77348,71435,63999,55542,55065,54788,50048,43324,34722,22139,14428,13107,164640,48915,285553,97299,433780,761696,728028,685183,177768,157259,127720,49674,33.1,100.5,21.3,47.6,7.1,7.9,8.4,7.6,6.8,7.4,7.6,7.0,6.3,5.5,5.4,5.4,4.9,4.3,3.4,2.2,1.4,1.3,16.2,4.8,28.2,9.6,42.8,75.1,71.8,67.6,17.5,15.5,12.6,508152,7.3,8.5,8.1,7.6,6.9,7.5,7.7,7.3,6.3,5.5,5.5,5.5,4.7,4.1,3.2,1.9,1.3,0.8,505429,35139,36494,43678,38667,33854,36498,38046,34213,31820,27434,26962,26834,26017,22301,18651,12241,7582,8998,7.0,7.2,8.6,7.7,6.7,7.2,7.5,6.8,6.3,5.4,5.3,5.3,5.1,4.4,3.7,2.4,1.5,1.8

<font color="blue">2nd Merge: Income/Population and Voter data. Same # of rows.<font>

In [208]:
merge2 = pd.concat([merge1, vdf], axis =1)

In [209]:
merge2['County'] = merge2['County'].apply(lambda x:x.strip())

In [210]:
# Saving merge2
merge2.to_parquet('data/cleaned/county.parquet', index=False)

<font color="blue">3rd Merge: Income/Population/Voter and Listings<font>

In [211]:
#Creating a dataframe based on merge2's columns

test2 = pd.DataFrame(columns = merge2.columns)

In [212]:
test2.shape

(0, 174)

In [213]:
#Iterrating over merge2's information. Based on the 'County' name in ldf dataframe, it will map over that 'County' info from merge2.
for idx, county in ldf['County'].iteritems():
    test2 = pd.concat([test2, merge2[merge2['County'] == county].copy()], ignore_index=True)

/var/folders/3j/my4n0ykx0yb51nj_xv6qbxp40000gn/T/ipykernel_9841/1753315747.py:2: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for idx, county in ldf['County'].iteritems():

In [214]:
df = pd.concat([ldf, test2.drop(columns = 'County')], axis=1)

df.shape

(17585, 190)

In [219]:
print(list(df.columns))

['Address', 'City', 'Zip', 'County', 'APN', 'Property Type', 'Bedrooms', 'Total Bathrooms', 'Building Sqft', 'Lot Size Sqft', 'Effective Year Built', 'Total Assessed Value', 'Est. Value', 'MLS Status', 'MLS Date', 'MLS Amount', 'Lien', 'W_HH_Income_<10k', 'W_HH_Income_$10,000 to $14,999', 'W_HH_Income_$15,000 to $19,999', 'W_HH_Income_$20,000 to $24,999', 'W_HH_Income_$25,000 to $29,999', 'W_HH_Income_$30,000 to $34,999', 'W_HH_Income_$35,000 to $39,999', 'W_HH_Income_$40,000 to $44,999', 'W_HH_Income_$45,000 to $49,999', 'W_HH_Income_$50,000 to $59,999', 'W_HH_Income_$60,000 to $74,999', 'W_HH_Income_$75,000 to $99,999', 'W_HH_Income_$100,000 to $124,999', 'W_HH_Income_$125,000 to $149,999', 'W_HH_Income_$150,000 to $199,999', 'W_HH_Income_$200,000 or more', 'Median_HH_Income', 'Median_HH_Income_B_AA', 'Median_HH_Income_Asian', 'Median_HH_Income_White', 'Total_Income', 'Passive_Income', 'Active_Income', 'SE_Income', 'Non_SE_Income', 'Total population', 'Population Under 5 years', 'Population  5-9 years', 'Population 10-14 years', 'Population 15-19 years', 'Population 20-24 years', 'Population 25-29 years', 'Population 30-34 years', 'Population 35-39 years', 'Population 40-44 years', 'Population 45-49 years', 'Population 50-54 years', 'Population  55-59 years', 'Population 60-64 years', 'Population 65-69 years', 'Population 70-74 years', 'Population 75-79 years', 'Population 80-84 years', 'Population Over 85 years', 'Population 5-14 years', 'Population Under 15-17 years', 'Population Under 18 years', 'Population Under 18-24 years', 'Population Under 15-44 years', 'Population Under 16 years and over', 'Population 18 years and over', 'Population 21 years and over', 'Population 60 years and over', 'Population 62 years and over', 'Population 65 years and over', 'Population 75 years and over', 'Median age (years)', 'Sex ratio (males per 100 females)', 'Old-age dependency ratio', 'Child dependency ratio', 'Percent Under 5 years', 'Percent 5 to 9 years', 'Percent 10 to 14 years', 'Percent 15 to 19 years', 'Percent 20 to 24 years', 'Percent 25 to 29 years', 'Percent 30 to 34 years', 'Percent 35 to 39 years', 'Percent 40 to 44 years', 'Percent 45 to 49 years', 'Percent 50 to 54 years', 'Percent 55 to 59 years', 'Percent 60 to 64 years', 'Percent 65 to 69 years', 'Percent 70 to 74 years', 'Percent 75 to 79 years', 'Percent 80 to 84 years', 'Percent 85 years and over', 'Percent 5 to 14 years', 'Percent 15 to 17 years', 'Percent Under 18 years', 'Percent 18 to 24 years', 'Percent 15 to 44 years', 'Percent 16 years and over', 'Percent 18 years and over', 'Percent 21 years and over', 'Percent 60 years and over', 'Percent 62 years and over', 'Percent 65 years and over', 'Male Total population', 'Percent Male Under 5 years', 'Percent Male 5 to 9 years', 'Percent Male 10 to 14 years', 'Percent Male 15 to 19 years', 'Percent Male 20 to 24 years', 'Percent Male 25 to 29 years', 'Percent Male 30 to 34 years', 'Percent Male 35 to 39 years', 'Percent Male 40 to 44 years', 'Percent Male 45 to 49 years', 'Percent Male 50 to 54 years', 'Percent Male 55 to 59 years', 'Percent Male 60 to 64 years', 'Percent Male 65 to 69 years', 'Percent Male 70 to 74 years', 'Percent Male 75 to 79 years', 'Percent Male 80 to 84 years', 'Percent Male 85 years and over', 'Female Total population', 'Female population Under 5 years', 'Female population 5 to 9 years', 'Female population 10 to 14 years', 'Female population  5 to 19 years', 'Female population 20 to 24 years', 'Female population 25 to 29 years', 'Female population 30 to 34 years', 'Female population 35 to 39 years', 'Female population 40 to 44 years', 'Female population 45 to 49 years', 'Female population 50 to 54 years', 'Female population 55 to 59 years', 'Female population 60 to 64 years', 'Female population 65 to 69 years', 'Female population 70 to 74 years', 'Female population 75 to 79 years', 'Female population 80 to 84 years', 'Female population 85 years and over', 'Percent Female Under 5 years', 'Percent Female 5 to 9 years', 'Percent Female 10 to 14 years', 'Percent Female 15 to 19 years', 'Percent Female 20 to 24 years', 'Percent Female 25 to 29 years', 'Percent Female  30 to 34 years', 'Percent Female 35 to 39 years', 'Percent Female  40 to 44 years', 'Percent Female 45 to 49 years', 'Percent Female 50 to 54 years', 'Percent Female 55 to 59 years', 'Percent Female 60 to 64 years', 'Percent Female 65 to 69 years', 'Percent Female 70 to 74 years', 'Percent Female 75 to 79 years', 'Percent Female 80 to 84 years', 'Percent Female 85 years and over', 'county', '2020_#_precincts', '2020_eligible_to_register', '2020_registered_voters', '2020_precinct_voters', '2020_mail_voters', '2020_total_voters', '2020_%_mail_voters', '2020_turnout_registered', '2020_turnout_eligible', '2021_#_precincts', '2021_eligible_to_register', '2021_registered_voters', '2021_precinct_voters', '2021_mail_voters', '2021_total_voters', '2021_%_mail_voters', '2021_turnout_registered', '2021_turnout_eligible', '2022_#_precincts', '2022_eligible_to_register', '2022_registered_voters', '2022_precinct_voters', '2022_mail_voters', '2022_total_voters', '2022_%_mail_voters', '2022_turnout_registered', '2022_turnout_eligible']

In [220]:
#Saving DF for easy editing
df.to_parquet('data/cleaned/df_pre_rent.parquet', index=False)

In [2]:
df = pd.read_parquet('data/cleaned/df_pre_rent.parquet')
rent = pd.read_parquet('data/cleaned/rent_cleaned.parquet')

##### <font color="blue">Rental Data - Adding Additional Features and then Merging<font>
---
<font color="blue">These features had to wait to be added until after the rental data and listing data were both merged.<font>

<font color="blue">Variables & Formulas that will be used in our dataset<font>

In [3]:
#Real Estate Variables

interest = .065/12
property_tax = .0071
maintenance = .003
insurance = .0025
closing_costs = .04
mls_amt = df['MLS Amount']
term = 360

#Real Estate Formulas

#Principal: Balance of the loan to purchas at the MLS Amount and 25% down.
principal = (mls_amt*.75) +(mls_amt*closing_costs)

#Monthly Mortgage payment of principal and interest
mortgage = principal * (interest*((1+interest)**term))/ (((1+interest)**term)-1)

#Costs: Annual cost of the mortgate, insurance, property taxes, and property maintenance
Costs = (mortgage * 12) + (mls_amt * maintenance) + (mls_amt * insurance) + (mls_amt * property_tax)

In [4]:
#Commented out so not to rerun
#Formatting columns and cells for easy referencing

df.drop('county', axis=1, inplace=True)
df.columns = [x.lower() for x in df]
df.columns = df.columns.str.replace(' ', '_')
df['county'] = df['county'].replace(' ', '_', regex=True)
df['property_type'] = df['property_type'].replace(' ', '_', regex=True)
df['county'] = df['county'].replace([x.lower() for x in df])
# df['name_county'] = df['county'].copy

In [5]:
#Commented out so not to rerun
#Adding our Real Estate Variables as columns

df.insert(loc=17, column = 'principal', value = principal)
df.insert(loc=18, column = 'mortgage', value = mortgage)
df.insert(loc=19, column = 'costs', value = Costs)
df.insert(loc=20, column = 'price_per_sqft', value = 0)
df['price_per_sqft'] = (df['mls_amount']/  df['building_sqft'])

In [6]:
#Commented out so not to rerun
#The following lines of code are creating a DOM, Days on Market, column. This is a useful metric for investors. At this moment in the
#beginning of 2023 DOM is an increasing metric. As it increases, price trends downwards.

df.insert(loc =20, column = 'dom', value = 0)
df['dom'] = pd.Timestamp.today().strftime('%Y-%m-%d')

df.insert(loc =20, column = 'today', value = 0)
df['today'] = pd.Timestamp.today().strftime('%Y-%m-%d')

df['mls_date'] =  pd.to_datetime(df['mls_date'])
df['dom'] =  pd.to_datetime(df['dom'])
df['today'] =  pd.to_datetime(df['today'])

df['dom'] = (df['today'] - df['mls_date'])

df['today'] = pd.Timestamp.today().strftime('2023-1-11')

df['dom'] = df['dom'].dt.days

In [7]:
df['property_type'].value_counts()

Single_Family_Residential         14373
Condominium_(Residential)          3053
Residential_(General)_(Single)      122
Townhouse_(Residential)              37
Name: property_type, dtype: int64

In [8]:
#After looking at the Value Counts of Property types, I decided to drop 2/4 values.
#I also relabeled the other two Values for Plotting purposes.

df = df.loc[~((df['property_type'] == 'Residential_(General)_(Single)') | (df['property_type'] == 'Townhouse_(Residential)'))]

df['property_type'] = df['property_type'].replace('Single_Family_Residential', 'SFR', regex=True)
df['property_type'] = df['property_type'].replace('[()]', '', regex=True)
df['property_type'] = df['property_type'].replace('Condominium_Residential', 'Condo', regex=True)

In [9]:
#Commented out so not to rerun
#Setting Index to Zip column for Mapping of Rental Data

rent.set_index('Unnamed: 0', inplace = True)
rent.index.rename('zip', inplace = True)

#Inserting Rental Information by mapping to the specific County and # of Beds. Turning our rental information into 
#useful data. The next 3 cells calculate annual revenue for each unit at the obsserved minimum, average, and maximum.


def transform(x):
    code = x['zip']
    beds = x['bedrooms']
    if code in rent.index:
        return rent.loc[code, f'bed{beds}_minRent']
df.insert(loc=21, column = 'min_annual_rent', value = 12*(df.apply(transform, axis = 1)))

def transform(x):
    code = x['zip']
    beds = x['bedrooms']
    if code in rent.index:
        return rent.loc[code, f'bed{beds}_averageRent']   
df.insert(loc=22, column = 'avg_annual_rent', value = 12*(df.apply(transform, axis = 1)))

def transform(x):
    code = x['zip']
    beds = x['bedrooms']
    if code in rent.index:
        return rent.loc[code, f'bed{beds}_maxRent']
df.insert(loc=23, column = 'max_annual_rent', value = 12*(df.apply(transform, axis = 1)))

In [10]:
#Commented out so not to rerun
#Calculating if the listing is profitable at our 3 levels of revenue.

df.insert(loc=24, column = 'min_cfp', value = 0)
df['min_cfp'] = (df['min_annual_rent'] - df['costs']) >0

df.insert(loc=25, column = 'avg_cfp', value = 0)
df['avg_cfp'] = (df['avg_annual_rent'] - df['costs']) >0

df.insert(loc=26, column = 'max_cfp', value = 0)
df['max_cfp'] = (df['max_annual_rent'] - df['costs']) >0

In [11]:
#Commented out so not to rerun
#These 3 items calculate the annual investment return on the initial investment needed to purchase the listing at the 
#current MLS Amount.

df.insert(loc=27, column = 'min_coc', value = 0)
df['min_coc'] = (df['min_annual_rent'] - df['costs'])/((closing_costs)+(df['mls_amount']*.25))

df.insert(loc=28, column = 'avg_coc', value = 0)
df['avg_coc'] = (df['avg_annual_rent'] - df['costs'])/((closing_costs)+(df['mls_amount']*.25))

df.insert(loc=29, column = 'max_coc', value = 0)
df['max_coc'] = (df['max_annual_rent'] - df['costs'])/((closing_costs)+(df['mls_amount']*.25))

In [16]:
df.insert(loc=30, column = 'target_cfp', value = 0)
df['target_cfp'] = (df['avg_coc']) > .04

##### <font color="blue">Final Conversions<font>
---

In [17]:
#Commented out so not to rerun

# df.drop(df.columns[3], axis=1, inplace=True)

#Rounding

decimals = 2    
df['mortgage'] = df['mortgage'].apply(lambda x: round(x, decimals))
decimals = 2    
df['costs'] = df['costs'].apply(lambda x: round(x, decimals))

#From boolean to binary

df['min_cfp'].replace({True: 1, False: 0}, inplace=True)
df['avg_cfp'].replace({True: 1, False: 0}, inplace=True)
df['max_cfp'].replace({True: 1, False: 0}, inplace=True)

#Adjusting percent numbers

df[['sex_ratio_(males_per_100_females)', 'old-age_dependency_ratio', 'child_dependency_ratio', 'percent_under_5_years', 'percent_5_to_9_years', 'percent_10_to_14_years', 
'percent_15_to_19_years', 'percent_20_to_24_years', 'percent_25_to_29_years', 'percent_30_to_34_years', 'percent_35_to_39_years', 'percent_40_to_44_years', 'percent_45_to_49_years', 
'percent_50_to_54_years', 'percent_55_to_59_years', 'percent_60_to_64_years', 'percent_65_to_69_years', 'percent_70_to_74_years', 'percent_75_to_79_years', 'percent_80_to_84_years', 
'percent_85_years_and_over', 'percent_5_to_14_years', 'percent_15_to_17_years', 'percent_under_18_years', 'percent_18_to_24_years', 'percent_15_to_44_years', 'percent_16_years_and_over', 
'percent_18_years_and_over', 'percent_21_years_and_over', 'percent_60_years_and_over', 'percent_62_years_and_over', 'percent_65_years_and_over', 'male_total_population', 'percent_male_under_5_years', 
'percent_male_5_to_9_years', 'percent_male_10_to_14_years', 'percent_male_15_to_19_years', 'percent_male_20_to_24_years', 'percent_male_25_to_29_years', 'percent_male_30_to_34_years', 
'percent_male_35_to_39_years', 'percent_male_40_to_44_years', 'percent_male_45_to_49_years', 'percent_male_50_to_54_years', 'percent_male_55_to_59_years', 'percent_male_60_to_64_years', 
'percent_male_65_to_69_years', 'percent_male_70_to_74_years', 'percent_male_75_to_79_years', 'percent_male_80_to_84_years', 'percent_male_85_years_and_over', 'percent_female_under_5_years', 
'percent_female_5_to_9_years', 'percent_female_10_to_14_years', 'percent_female_15_to_19_years', 'percent_female_20_to_24_years', 'percent_female_25_to_29_years', 'percent_female__30_to_34_years', 
'percent_female_35_to_39_years', 'percent_female__40_to_44_years', 'percent_female_45_to_49_years', 'percent_female_50_to_54_years', 'percent_female_55_to_59_years', 'percent_female_60_to_64_years', 
'percent_female_65_to_69_years', 'percent_female_70_to_74_years', 'percent_female_75_to_79_years', 'percent_female_80_to_84_years', 'percent_female_85_years_and_over']] = df[['sex_ratio_(males_per_100_females)', 
'old-age_dependency_ratio', 'child_dependency_ratio', 'percent_under_5_years', 'percent_5_to_9_years', 'percent_10_to_14_years', 
'percent_15_to_19_years', 'percent_20_to_24_years', 'percent_25_to_29_years', 'percent_30_to_34_years', 'percent_35_to_39_years', 'percent_40_to_44_years', 'percent_45_to_49_years', 
'percent_50_to_54_years', 'percent_55_to_59_years', 'percent_60_to_64_years', 'percent_65_to_69_years', 'percent_70_to_74_years', 'percent_75_to_79_years', 'percent_80_to_84_years', 
'percent_85_years_and_over', 'percent_5_to_14_years', 'percent_15_to_17_years', 'percent_under_18_years', 'percent_18_to_24_years', 'percent_15_to_44_years', 'percent_16_years_and_over', 
'percent_18_years_and_over', 'percent_21_years_and_over', 'percent_60_years_and_over', 'percent_62_years_and_over', 'percent_65_years_and_over', 'male_total_population', 'percent_male_under_5_years', 
'percent_male_5_to_9_years', 'percent_male_10_to_14_years', 'percent_male_15_to_19_years', 'percent_male_20_to_24_years', 'percent_male_25_to_29_years', 'percent_male_30_to_34_years', 
'percent_male_35_to_39_years', 'percent_male_40_to_44_years', 'percent_male_45_to_49_years', 'percent_male_50_to_54_years', 'percent_male_55_to_59_years', 'percent_male_60_to_64_years', 
'percent_male_65_to_69_years', 'percent_male_70_to_74_years', 'percent_male_75_to_79_years', 'percent_male_80_to_84_years', 'percent_male_85_years_and_over', 'percent_female_under_5_years', 
'percent_female_5_to_9_years', 'percent_female_10_to_14_years', 'percent_female_15_to_19_years', 'percent_female_20_to_24_years', 'percent_female_25_to_29_years', 'percent_female__30_to_34_years', 
'percent_female_35_to_39_years', 'percent_female__40_to_44_years', 'percent_female_45_to_49_years', 'percent_female_50_to_54_years', 'percent_female_55_to_59_years', 'percent_female_60_to_64_years', 
'percent_female_65_to_69_years', 'percent_female_70_to_74_years', 'percent_female_75_to_79_years', 'percent_female_80_to_84_years', 'percent_female_85_years_and_over'     
]].astype(float)/100

In [18]:
#Exporting Cleaned Final dataset.

df.to_parquet('data/cleaned/df_2.0.parquet', index=False)